### ISSUE TITLE
Commands are not running as op if setted runAs: op

### ISSUE THREAD

**Issue by TheAz928** [TheAz928/ItemCommands#1]
#Bug

**Comment by timbersquirrel** [comment]
maybe this can help:
https://forums.pmmp.io/threads/solved-run-command-as-player-or-console.2245/

**Comment by timbersquirrel** [comment]
@TheAz928

**Comment by TheAz928** [comment]
This won't help

**Comment by timbersquirrel** [comment]
Oh ok I am not really sure how this can be fixed, as I’m not rlly good at coding but i hope someone can fix this
