### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by BurritoMan46** [TheAz928/ItemCommands#7]
On The Configuration file I did "setgroup {name} Knight" and I restarted my server and it didn't work and item Id is 339:200 please help

Thanks For Reading This!

**Comment by TheAz928** [comment]
Post your configured file data here, that doesn't help much, also tell how you tested it. Lack of information will make this issue be closed and marked as invalid

**Comment by BurritoMan46** [comment]
Okay Thanks I'll Try

**Comment by BurritoMan46** [comment]
I did this : 
"339:200":
  name: "Â§aVoucher"
  lore:
    - "Grants Knight Rank"
   runAs: 0
   commands:
     - "setgroup {name} Knight"

Then I restarted my server I /give 339:200 and it didn't worked at all

**Comment by BurritoMan46** [comment]
And this is my configuration file : 

---
# ItemCommands configuration file
# Developed by TheAz928
# Format:
# "ID:DAMAGE":
#    runAs: player/console/asop
#    commands:
#      - " "
#      - " "
#    name: test
#    lore:
#      - " "
# TAGS:
# {name} - Player name
# {tag} - Player Name tag
# {level} - Player world name
# {x} - Player x
# {y} - Player y
# {z} - Player z
# RUN_AS:
#    0 - player
#    1 - op
#    2 - console
"339:100":
  name: "Â§aVoucher"
  lore:
    - "Grants 1000$"
  runAs: 0
  commands:
    - "givemoney {name} 1000"
---
"339:200":
  name: "Â§aVoucher"
  lore:
    - "Grants Knight Rank"
   runAs: 0
   commands:
     - "setgroup {name} Knight"

...

**Comment by TheAz928** [comment]
Any errors? Have you checked if the plugin was even loaded ?

**Comment by BurritoMan46** [comment]
It was loaded and the voucher that grants 1000$ was working but I made another one for setting a rank it didn't work

**Comment by BurritoMan46** [comment]
So?? What Do I Do?

**Comment by BurritoMan46** [comment]
Hello???

**Comment by TheAz928** [comment]
I've  checked, but it didn't got me the error

**Comment by BurritoMan46** [comment]
So what do I do?

**Comment by TheAz928** [comment]
Nothing to do, since I can't check it deeply and don't have time to also, it loads multiple items as I tested, that's all I have to say

**Comment by TheAz928** [comment]
By saying I can't check it deeply meaning that I can't check your server, your configurations, your plugins, and this plugin deeply
