### ISSUE TITLE
Enchanted Item

### ISSUE THREAD

**Issue by SpecialistNinja** [TheAz928/ItemCommands#9]
Doesn't support enchanted item

"277:5":
  name: "Magic Shovel"
  lore:
    - "Tap For Better Shovel"
  runAs: 2
  commands:
    - "give {name} 277 1  {display:{Name:"Diamond Shovel"}{ench:[{id:15s,lvl:4s} {id:17s,lvl:3s} {id:18s,lvl:3s}]}"

ERROR:

16.01 01:57:12 [Server] Server thread/INFO Loading ItemCommands v1.0.0
16.01 01:57:12 [Server] Server thread/INFO Loading items...
16.01 01:57:12 [Server] Server thread/CRITICAL ErrorException: "yaml_parse(): parsing error encountered during parsing: did not find expected '-' indicator (line 43, column 43), context while parsing a block collection (line 43, column 5)" (EXCEPTION) in "src/pocketmine/utils/Config" at line 155
16.01 01:57:12 [Server] Server thread/DEBUG #0 (): pocketmine\error_handler(integer 2, string yaml_parse(): parsing error encountered during parsing: did not find expected '-' indicator (line 43, column 43), context while parsing a block collection (line 43, column 5), string phar:///custom-php7.2.phar/src/pocketmine/utils/Config.php, integer 155, array Array())
16.01 01:57:12 [Server] Server thread/DEBUG #1 src/pocketmine/utils/Config(155): yaml_parse(string ---..# ItemCommands configuration file..# Developed by TheAz928....# If the item should be removed after usage..settings:..  remove-items: true....# Format:..# "ID:DAMAGE":..#    runAs: player/console/asop..#    commands:..#      - " "..#      - " "..#    name: test..#    lore:..#      - " "..# TAGS:..# {name} - Player name..# {tag} - Player Name tag..# {level} - Player world name..# {x} - Player x..# {y} - Player y..# {z} - Player z..# RUN_AS:..#    0 - player..#    1 - op..#    2 - console.."339:100":..  name: "..aVoucher"..  lore:..    - "Grants 100$"..  runAs: 2..  commands:..    - "givemoney {name} 100"...."277:5":..  name: "Magic Shovel"..  lore:..    - "Tap For Better Shovel"..  runAs: 2..  commands:..    - "give {name} 277 1  {display:{Name:"Diamond Shovel"}{ench:[{id:15s,lvl:4s} {id:17s,lvl:3s} {id:18s,lvl:3s}]".....)
16.01 01:57:12 [Server] Server thread/DEBUG #2 src/pocketmine/utils/Config(86): pocketmine\utils\Config->load(string /plugins/ItemCommands/config.yml, integer -1, array Array())
16.01 01:57:12 [Server] Server thread/DEBUG #3 src/pocketmine/plugin/PluginBase(264): pocketmine\utils\Config->__construct(string /plugins/ItemCommands/config.yml)
16.01 01:57:12 [Server] Server thread/DEBUG #4 src/pocketmine/plugin/PluginBase(244): pocketmine\plugin\PluginBase->reloadConfig()
16.01 01:57:12 [Server] Server thread/DEBUG #5 ItemCommands_dev-6 (1).phar/src/ItemCommands/Core(22): pocketmine\plugin\PluginBase->getConfig()
16.01 01:57:12 [Server] Server thread/DEBUG #6 src/pocketmine/plugin/PharPluginLoader(112): ItemCommands\Core->onLoad()
16.01 01:57:12 [Server] Server thread/DEBUG #7 src/pocketmine/plugin/PharPluginLoader(65): pocketmine\plugin\PharPluginLoader->initPlugin(ItemCommands\Core object, pocketmine\plugin\PluginDescription object, string /plugins/ItemCommands, string phar:///plugins/ItemCommands_dev-6 (1).phar)
16.01 01:57:12 [Server] Server thread/DEBUG #8 src/pocketmine/plugin/PluginManager(161): pocketmine\plugin\PharPluginLoader->loadPlugin(string phar:///plugins/ItemCommands_dev-6 (1).phar)
16.01 01:57:12 [Server] Server thread/DEBUG #9 src/pocketmine/plugin/PluginManager(305): pocketmine\plugin\PluginManager->loadPlugin(string /plugins/ItemCommands_dev-6 (1).phar, array Array())
16.01 01:57:12 [Server] Server thread/DEBUG #10 AllAPILoader-ALPHA9.phar/src/TheNewHEROBRINE/AllAPILoader/Main(22): pocketmine\plugin\PluginManager->loadPlugins(string /plugins/, array Array())
16.01 01:57:12 [Server] Server thread/DEBUG #11 src/pocketmine/plugin/PluginBase(90): TheNewHEROBRINE\AllAPILoader\Main->onEnable()
16.01 01:57:12 [Server] Server thread/DEBUG #12 src/pocketmine/plugin/PharPluginLoader(122): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
16.01 01:57:12 [Server] Server thread/DEBUG #13 src/pocketmine/plugin/PluginManager(610): pocketmine\plugin\PharPluginLoader->enablePlugin(TheNewHEROBRINE\AllAPILoader\Main object)
16.01 01:57:12 [Server] Server thread/DEBUG #14 src/pocketmine/Server(1955): pocketmine\plugin\PluginManager->enablePlugin(TheNewHEROBRINE\AllAPILoader\Main object)
16.01 01:57:12 [Server] Server thread/DEBUG #15 src/pocketmine/Server(1941): pocketmine\Server->enablePlugin(TheNewHEROBRINE\AllAPILoader\Main object)
16.01 01:57:12 [Server] Server thread/DEBUG #16 PocketMine-DevTools_dev-83 (1).phar/src/DevTools/DevTools(49): pocketmine\Server->enablePlugins(integer 0)
16.01 01:57:12 [Server] Server thread/DEBUG #17 src/pocketmine/plugin/PluginBase(90): DevTools\DevTools->onEnable()
16.01 01:57:12 [Server] Server thread/DEBUG #18 src/pocketmine/plugin/PharPluginLoader(122): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
16.01 01:57:12 [Server] Server thread/DEBUG #19 src/pocketmine/plugin/PluginManager(610): pocketmine\plugin\PharPluginLoader->enablePlugin(DevTools\DevTools object)
16.01 01:57:12 [Server] Server thread/DEBUG #20 src/pocketmine/Server(1955): pocketmine\plugin\PluginManager->enablePlugin(DevTools\DevTools object)
16.01 01:57:12 [Server] Server thread/DEBUG #21 src/pocketmine/Server(1941): pocketmine\Server->enablePlugin(DevTools\DevTools object)
16.01 01:57:12 [Server] Server thread/DEBUG #22 src/pocketmine/Server(1655): pocketmine\Server->enablePlugins(integer 0)
16.01 01:57:12 [Server] Server thread/DEBUG #23 src/pocketmine/PocketMine(554): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /, string /plugins/)
16.01 01:57:12 [Server] Server thread/DEBUG #24 /custom-php7.2.phar(1): require(string phar:///custom-php7.2.phar/src/pocketmine/PocketMine.php)
16.01 01:57:12 [Server] Server thread/CRITICAL Could not load plugin 'ItemCommands'

**Comment by SpecialistNinja** [comment]
When i removed the "{display:{Name:"Diamond Shovel"}{ench:[{id:15s,lvl:4s} {id:17s,lvl:3s} {id:18s,lvl:3s}]}" it work once again

**Comment by TheAz928** [comment]
Something is wrong with your config/command writing

**Comment by SpecialistNinja** [comment]
Could u tell me what i did wrong, i don't see anything wrong here

---
# ItemCommands configuration file
# Developed by TheAz928

# If the item should be removed after usage
settings:
  remove-items: true

# Format:
# "ID:DAMAGE":
#    runAs: player/console/asop
#    commands:
#      - " "
#      - " "
#    name: test
#    lore:
#      - " "
# TAGS:
# {name} - Player name
# {tag} - Player Name tag
# {level} - Player world name
# {x} - Player x
# {y} - Player y
# {z} - Player z
# RUN_AS:
#    0 - player
#    1 - op
#    2 - console
"339:100":
  name: "§aVoucher"
  lore:
    - "Grants 100$"
  runAs: 2
  commands:
    - "givemoney {name} 100"
"277:5":
  name: "Magic Shovel"
  lore:
    - "Tap For Better Shovel"
  runAs: 2
  commands:
    - "give {name} 277 1 {display:{Name:"Diamond Shovel"}{ench:[{id:15s,lvl:4s} {id:17s,lvl:3s} {id:18s,lvl:3s}]}"
...

THANK YOU

**Comment by DenielWorld** [comment]
You have "" inside another ""
